services:
  docs-nagomi-ft-macro:
    container_name: docs-nagomi-ft-macro
    networks:
      default:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./src:/work
    tty: true
    restart: always
    ports:
      - 4321:4321